### ISSUE TITLE
cant run on Mac os

### ISSUE THREAD

**Issue by gedw99** [deranjer/goTorrent#20]
x-MacBook-Pro:goTorrent apple$ go run main.go
Failed creating 64-bit integer for goTorrent Port! strconv.ParseInt: parsing ":8000": invalid syntax
Logging to file logs/server.log
exit status 1

env:

go version go1.11.4 darwin/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build741379552=/tmp/go-build -gno-record-gcc-switches-fno-common"

**Comment by deranjer** [comment]
Okay, this will be tough since I don't own a Mac to test on. Is there anything in the server.log file? There might not be if it fails before a write to the log. Also I think I'm running a slightly older version of go, Ill upgrade to the latest and test.

I have gotten the 64-bit injure message before on Linux with the latest version of gotorrent, but it wasn't a fatal error. Hopefully when I'm home tonight I can take a further look.

**Comment by deranjer** [comment]
@gedw99 Okay, I've pushed an update that will fix the port error, but that shouldn't have been fatal to begin with.  I also tested with the latest version of Go to verify it works (on Windows).  Until you post the server.log file I can't do any more debugging.

**Comment by deranjer** [comment]
No response, closing issue.
