### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by nk932714** [deranjer/goTorrent#7]
Failed to deploy on heroku

**Comment by deranjer** [comment]
I have never used Heroku, so I'm going to need WAY more information than that.

**Comment by nk932714** [comment]
heroku is a free platform to deploy your app. 
If you haven't tried yet then give it a try. It will not take more then one or two minutes. 
steps to reproduce the problem
1. https://www.heroku.com/
2. create any app ( only app name is required)
3. Connect with github 
4. Search for goTorrent repo
5. Click on deploy app


I am facing the issue that heroku is unable to detect the language automatically.
If i manually select the language then it give the error that ```App not compatible with buildpack```

**Comment by deranjer** [comment]
https://devcenter.heroku.com/articles/go-support  

As far as I can tell from the documentation, Heroku requires you to use a dependency management library like godep which bundles all of the libraries your app requires into a /src folder (or something like that).  

I don't use dependency management for this application, and certainly don't plan on using it anytime soon, certainly not before the 1.0 release which is looking like somewhere around 2019.  Since this is the alpha I am fine with using bleeding edge versions of all my libraries, and don't feel like updating godep dependencies everytime a new push comes out from my torrent library.

You are welcome to fork the repo and add something like godep, it looks fairly simple to add, after the 1.0 release I will accept a PR for godep since I will want to be more stable at that point.

**Comment by nk932714** [comment]
Thanks bro for info
